### ISSUE TITLE
Cảm ơn bạn/anh rất nhiều!!!

### ISSUE THREAD

**Issue by TrungThinhScorpius** [pth-1641/NComics#3]
Mình mới từ backend sang frontend, củng rất thích đọc truyện tranh. Nên đã quyết định làm một dự án đọc truyện bằng nuxtjs để học hỏi nâng cao trình độ. Source code này rất tốt, có nhiều thứ để học hỏi. Xin phép bạn/anh cho mình sử dụng source code này. Xin chân thành cảm ơn bạn/anh rất nhiều. どうもありがとうございます.

**Comment by Muphet** [comment]
where is the api source?
