### ISSUE TITLE
An unexpected error occurred: "https://registry.yarnpkg.com/comics-api/-/comics-api-2.8.7.tgz: Request failed \"404 Not Found\

### ISSUE THREAD

**Issue by fool-cats** [pth-1641/NComics#4]
How to solve this problem, it shows me that the package can't be found

**Comment by pth-1641** [comment]
@fool-cats Sorry for the inconvenience. This package has been removed from NPM. You can try using the [this](https://github.com/pth-1641/Comics-API)
